### ISSUE TITLE
Entities created by this integration do not support long-term statistics?

### ISSUE THREAD

**Issue by hiatsu0** [PlusPlus-ua/ha_mobilealerts#17]
Just noticed while browsing some of my weather data that the entities created by this integration may not be supporting [long-term statistics](https://data.home-assistant.io/docs/statistics/), as the data stops at my `recorder`'s  `purge_keep_days` -setting of 60 days. Many other entities do have long-term statistics, like for example the forecasted temperature in my case:

<img width="1268" alt="image" src="https://github.com/PlusPlus-ua/ha_mobilealerts/assets/66969014/6d371676-833d-4dcb-955d-d3e4185bc350">

Is there any way to force statistics creation for the MobileAlerts' entities, or does something need to be changed in the integration itself to gain support for statistics?

My guess is that the `state_class: measurement` might be the key here? The template sensor I have for recording the current forecast has this:

```
template:
  - sensor:
      # Collecting weather forecast:
      - name: forecast_temperature
        state: "{{ state_attr('weather.forecast_myplace','temperature') }}"
        unit_of_measurement: "°C"
        state_class: measurement
```
